def REVC(s):
    complement = {'A': 'T', 'T': 'A', 'C': 'G', 'G': 'C'}
    out = ''
    for b in s:
        out += complement[b]
    return out[::-1]


print(REVC(
    'CATCTTGTGAACACCCTAGGCACGCCGTCCCTGCGATCCCACCCGGTGTCAGCGAAGCCTTGACGATCCAACAACAGGGATGAGCGGTCATGAGAATAACCGTCATCCCAAAACCGGCACGCTCCAAGCCACACAAAAACCTATAGATAAGGTGTAGCTTGGTCTCGTACCCTGATTGGGTTTTCGCTCGGAAGGCTAGTGCGTCCTTGGTGACCTGTGCCTACACAAGTAGCTATTAATGCAGTATCGTAGCGCATAATGCTCTATAATCGCTCTTAACGCGCTTAAACACTGTTTGAGCATCGGGCCAACGATACCTCGCCGACTAACACCGTCAATTCCCATTGAATCACCAACCCTCGGCGCTAGATGTAAGGGGTATGATTTAGCCAGTCGCCCTAAATTTATTGATGACGCCGACAGCACCCTCATCTGGGGGCTTCCCAATTTCTGTCTGCAGCTGTGTGGTAATAAAACGGGCATTCGAACGTTTCATCCGTTGCTATACAAATGACTTTGAGGGTAATAGAGGGTCACCATGAGTAGAACACTTAAATCGCACTCTCCAGTATGCTGCGCTCTGCCGACTCCGGCTACCCGGTCGAGTACATACCATCGGAAAGTCTCCCGTTTACTCCTTTAGTCGAGAGCCCGTGGGATTGTAGAACGTGAAAGACCTCTCTCGCGAGTAGTTGCAGGGTAGTTTGTGTGAGAAGGATAATCAGTTCAAATCCGCCTTGTACGGAGCATATAACATGCGTCCAGCTCAAAAATTTCTTAATGCTGCGAGCTGGACCAGTCCGATGGA'))
