s = 'AGCCCGCAGCCCGCGAGCGCAGCCCGCGAAGCCCGCCTTAAGCCCGCAAAGCCCGCGCGAAGCCCGCGCAGCCCGCCTCATCGGTCTAGCCCGCACAGCCCGCGTAGCCCGCTAAGCCCGCAGCCCGCATGACTTAGCCCGCCAGCCCGCGGGAGCCCGCAAACAGCCCGCAGCCCGCTTCAGCCCGCAGCCCGCCTGAGCCCGCAAGCCCGCAGCCCGCGAGCCCGCGAGCCCGCAGCCCGCAGCCCGCTTAAAATGGACCCAGCCCGCACAGCCCGCACAGCCCGCCGAGCCCGCATGAGCCCGCCGAGCCCGCCAGCCCGCAAGCCCGCGGTTTCCGTAAGCCCGCTTGGTGTAGCCCGCGTAGCCCGCGGGATGAAGCCCGCAGCGGAGCGAGCCCGCAGCCCGCCAGCCCGCAGCCCGCGCAGCCCGCTCAGCCCGCTTAGAGCCCGCGAGCCCGCTCAACAGCTCAGCCCGCAGCCCGCATCATAGCCCGCAGCCCGCAGCCCGCAGCCCGCCCCAGAACCAATGGAGCCCGCTGCGAGCCCGCAGCCCGCTCTAGCCCGCCGAGCTAGCCCGCAGCCCGCAGCCCGCAGCCCGCAGCCCGCATAGCCCGCCCGACAAGCCCGCACTCAGCCCGCTGTGTGCGAGTAGCCCGCAGCCCGCATAGCCCGCACTAGTAGAAGCCCGCTAAAGTCTTGGTCAGCCCGCAGAGCCCGCCCTGCGAGCCCGCGGCAGAGCCCGCGCCGAGCCCGCAGCCCGCATATAGCCCGCTAGCCCGCTTACTCAGCCCGCAGCCCGCACCGTTAAC'
t = 'AGCCCGCAG'

pos = []

while s.count(t) != 0:
    if len(pos) == 0:
        pos.append(s.index(t) + 1)
    else:
        pos.append(s.index(t) + 1 + pos[-1])
    s = s[s.index(t) + 1:]

print(' '.join(pos))
